CREATE TABLE "ADPI_DXR"."SPARK_DATA_SYNC_CATALOG"
  (
     "SOURCE_TABLE"           VARCHAR2(200 BYTE) NOT NULL ENABLE,
     "SOURCE_SCHEMA"          VARCHAR2(200 BYTE) NOT NULL ENABLE,
     "TARGET_SCHEMA"          VARCHAR2(200 BYTE) NOT NULL ENABLE,
     "FORCE_SYNC_DAY_OF_MNTH" NUMBER(2, 0) DEFAULT 0 NOT NULL ENABLE,
     "ACTIVE"                 NUMBER(1, 0) DEFAULT 1 NOT NULL ENABLE,
     "MAX_HIST_PARTITIONS"    NUMBER(4, 0) DEFAULT 0 NOT NULL ENABLE,
     "IS_VIEW"                NUMBER(1, 0) DEFAULT 0 NOT NULL ENABLE,
     "INSERT_DATE"            DATE DEFAULT SYSDATE NOT NULL ENABLE,
     CONSTRAINT "SPARK_DATA_SYNC_CATALOG_PK" PRIMARY KEY ("SOURCE_TABLE",
     "SOURCE_SCHEMA", "TARGET_SCHEMA")
  );