REM INSERTING into SPARK_DATA_SYNC_CATALOG
SET DEFINE OFF;
-- BASE_DB tables
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('janzz_output_master','dc1dsbase','livedsbasedc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('client_ownership_type_monthly','dc1dsbase','livedsbasedc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('client_base_monthly','dc1dsbase','livedsbasedc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('client_core_master','dc1dsbase','livedsbasedc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('ap_monthly_company_ein','dc1dsbase','livedsbasedc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('ap_monthly','dc1dsbase','livedsbasedc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('client_master','dc1dsbase','livedsbasedc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('client_monthly','dc1dsbase','livedsbasedc1',0,1,0,0);

Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('employee_base_monthly','dc1dsbase','livedsbasedc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('nas_establishment','dc1dsbase','livedsbasedc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('nas_work_location','dc1dsbase','livedsbasedc1',0,1,0,0);

-- MAIN_DB tables
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('t_dim_known_commutes','dc1dsmain','livedsmaindc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('t_dim_zip_lat_long','dc1dsmain','livedsmaindc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('termination_reasons_classified','dc1dsmain','livedsmaindc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('t_dim_client_industries','dc1dsmain','livedsmaindc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('span_ctrl_core','dc1dsmain','livedsmaindc1',0,1,0,0);

-- RAW_DB tables
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('ezlm_ezlmoid','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('ezlm_fact_payroll_time','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('t_dim_day','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('totalsource_dim_client','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('totalsource_dim_company','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('totalsource_dim_department','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('totalsource_dim_establishment','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('totalsource_dim_eventtype','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('totalsource_dim_job','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('totalsource_dim_paygroup','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('totalsource_dim_person','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('totalsource_dim_person_dt','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('totalsource_dim_worklocation','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('totalsource_fact_workassignment','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('totalsource_fact_workassignmentevent','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('wfn_fact_workassignment','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('wfn_pay_grades','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('wfn_paycode','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('wfn_person','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('wfn_time_payrl','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('wfn_time_suppl','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('wfn_work_state','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('totalsource_client','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('etime_time','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('etime_paycode','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('dw_paycodes_labelled_dataset','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('nas_xtrct_establishments','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('naicsvalidated','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('industry_hierarchy','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('esdb_tts_client_master','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('esdb_prospect_monthly','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('esdb_client_master','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('esdb_business_unit','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('dw_t_clnt_prfl_setting','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('client360','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('dw_v_job_map','dc1dsraw','livedsrawdc1',0,1,0,0);
Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('optout','dc1dsraw','livedsrawdc1',0,1,0,0);
-- Insert into SPARK_DATA_SYNC_CATALOG (SOURCE_TABLE,SOURCE_SCHEMA,TARGET_SCHEMA,FORCE_SYNC_DAY_OF_MNTH,ACTIVE,MAX_HIST_PARTITIONS,IS_VIEW) values ('wfn_location','dc1dsraw','livedsrawdc1',0,1,0,0);
