CREATE OR REPLACE PROCEDURE [OWNERID].post_ins_export()
	LANGUAGE plpgsql
AS $$

BEGIN 

--EXECUTE 'TRUNCATE TABLE [OWNERID].TMP_T_FACT_INS_LOG';
EXECUTE 'DROP TABLE IF EXISTS [OWNERID].TMP_T_FACT_INS_LOG';
EXECUTE 'CREATE TABLE IF NOT EXISTS [OWNERID].TMP_T_FACT_INS_LOG(clnt_obj_id VARCHAR (100), row_count INTEGER)';

EXECUTE 'DELETE  FROM [OWNERID].t_fact_ins WHERE CLNT_OBJ_ID IN (SELECT DISTINCT CLNT_OBJ_ID FROM [OWNERID].T_FACT_INS_STG)';

EXECUTE 'INSERT INTO [OWNERID].t_fact_ins
            SELECT 
             *
             FROM [OWNERID].T_FACT_INS_STG';

EXECUTE 'INSERT INTO [OWNERID].TMP_T_FACT_INS_LOG 
          SELECT CLNT_OBJ_ID, COUNT(*) from 
              [OWNERID].T_FACT_INS_STG
               group by clnt_obj_id';

EXECUTE 'DELETE  FROM [OWNERID].t_fact_ins WHERE CLNT_OBJ_ID IN (SELECT DISTINCT clnt_obj_id FROM T_CLNT WHERE clnt_live_clsfn = ''T'')';

COMMIT;
EXCEPTION WHEN OTHERS THEN 
ROLLBACK;
END;
$$
;


CALL [OWNERID].post_ins_export()