BEGIN
  EXECUTE IMMEDIATE 'TRUNCATE TABLE T_FACT_INS_STG';
  EXECUTE IMMEDIATE 'TRUNCATE TABLE T_INS_LOAD_STUS';
  EXECUTE IMMEDIATE 'TRUNCATE TABLE T_DIM_INS_ARM_STATS';
  EXECUTE IMMEDIATE 'TRUNCATE TABLE T_INS_SPLUNK_HIST';
  p_ins_prtn_crt;
END;