set hive.exec.dynamic.partition=true;
set hive.exec.dynamic.partition.mode=nonstrict;

DROP TABLE IF EXISTS ${hiveconf:__GREEN_MAIN_DB__}.t_fact_correlations;

CREATE TABLE IF NOT EXISTS ${hiveconf:__GREEN_MAIN_DB__}.t_fact_correlations (
       sector_cd string,
       yr_cd string,
       qtr_cd string,
       dimension string,
       num_records int,
       mtrc_ky string,
       mtrc_ky_corr_with string,
       diff string,
       corr_value double,
       corr_cnt int
) PARTITIONED BY (environment string, db_schema string) 
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';

INSERT OVERWRITE TABLE ${hiveconf:__GREEN_MAIN_DB__}.t_fact_correlations PARTITION(environment, db_schema)
   SELECT  
          sector_cd,
          yr_cd,
          qtr_cd,
          dimension,
          num_records,
          mtrc_ky,
          mtrc_ky_corr_with,
          diff,
          corr_value[0] as corr_value,
          corr_value[1] as corr_cnt,
          environment,
          db_schema
   FROM 
   (
        SELECT 
             qtr_cd,
             sector_cd,
             yr_cd,
             dimension,
             num_records,
             metrics.metric_ky_1 as mtrc_ky,
             metrics.metric_ky_2 as mtrc_ky_corr_with,
             CAST(metrics.metric_corr[0] AS DOUBLE) AS corr_0,
             CAST(metrics.metric_corr[1] AS DOUBLE) AS corr_1,
             CAST(metrics.metric_corr[2] AS DOUBLE) AS corr_2, 
             CAST(metrics.metric_cnt[0] AS DOUBLE)  AS cnt_0,
             CAST(metrics.metric_cnt[1] AS DOUBLE)  AS cnt_1,
             CAST(metrics.metric_cnt[2] AS DOUBLE)  AS cnt_2, 
             environment,
             db_schema
        FROM    
           (
            SELECT 
               qtr_cd,
               sector_cd,
               yr_cd,
               dimension,
               num_records,
               turnover_rate_newhire_turnover_corr,
               turnover_rate_average_tenure_corr,
               turnover_rate_avg_time_to_promotion_corr,
               turnover_rate_average_earnings_corr,
               turnover_rate_absence_perc_corr,
               turnover_rate_overtime_perc_corr,
               newhire_turnover_turnover_rate_corr,
               newhire_turnover_average_tenure_corr,
               newhire_turnover_avg_time_to_promotion_corr,
               newhire_turnover_average_earnings_corr,
               newhire_turnover_absence_perc_corr,
               newhire_turnover_overtime_perc_corr,
               average_tenure_turnover_rate_corr,
               average_tenure_newhire_turnover_corr,
               average_tenure_avg_time_to_promotion_corr,
               average_tenure_average_earnings_corr,
               average_tenure_absence_perc_corr,
               average_tenure_overtime_perc_corr,
               avg_time_to_promotion_turnover_rate_corr,
               avg_time_to_promotion_newhire_turnover_corr,
               avg_time_to_promotion_average_tenure_corr,
               avg_time_to_promotion_average_earnings_corr,
               avg_time_to_promotion_absence_perc_corr,
               avg_time_to_promotion_overtime_perc_corr,
               average_earnings_turnover_rate_corr,
               average_earnings_newhire_turnover_corr,
               average_earnings_average_tenure_corr,
               average_earnings_avg_time_to_promotion_corr,
               average_earnings_absence_perc_corr,
               average_earnings_overtime_perc_corr,
               overtime_perc_turnover_rate_corr,
               overtime_perc_newhire_turnover_corr,
               overtime_perc_average_tenure_corr,
               overtime_perc_avg_time_to_promotion_corr,
               overtime_perc_average_earnings_corr,
               overtime_perc_absence_perc_corr,
               absence_perc_turnover_rate_corr,
               absence_perc_newhire_turnover_corr,
               absence_perc_average_tenure_corr,
               absence_perc_avg_time_to_promotion_corr,
               absence_perc_average_earnings_corr,
               absence_perc_overtime_perc_corr,
               turnover_rate_newhire_turnover_cnt,
               turnover_rate_average_tenure_cnt,
               turnover_rate_avg_time_to_promotion_cnt,
               turnover_rate_average_earnings_cnt,
               turnover_rate_absence_perc_cnt,
               turnover_rate_overtime_perc_cnt,
               newhire_turnover_turnover_rate_cnt,
               newhire_turnover_average_tenure_cnt,
               newhire_turnover_avg_time_to_promotion_cnt,
               newhire_turnover_average_earnings_cnt,
               newhire_turnover_absence_perc_cnt,
               newhire_turnover_overtime_perc_cnt,
               average_tenure_turnover_rate_cnt,
               average_tenure_newhire_turnover_cnt,
               average_tenure_avg_time_to_promotion_cnt,
               average_tenure_average_earnings_cnt,
               average_tenure_absence_perc_cnt,
               average_tenure_overtime_perc_cnt,
               avg_time_to_promotion_turnover_rate_cnt,
               avg_time_to_promotion_newhire_turnover_cnt,
               avg_time_to_promotion_average_tenure_cnt,
               avg_time_to_promotion_average_earnings_cnt,
               avg_time_to_promotion_absence_perc_cnt,
               avg_time_to_promotion_overtime_perc_cnt,
               average_earnings_turnover_rate_cnt,
               average_earnings_newhire_turnover_cnt,
               average_earnings_average_tenure_cnt,
               average_earnings_avg_time_to_promotion_cnt,
               average_earnings_absence_perc_cnt,
               average_earnings_overtime_perc_cnt,
               overtime_perc_turnover_rate_cnt,
               overtime_perc_newhire_turnover_cnt,
               overtime_perc_average_tenure_cnt,
               overtime_perc_avg_time_to_promotion_cnt,
               overtime_perc_average_earnings_cnt,
               overtime_perc_absence_perc_cnt,
               absence_perc_turnover_rate_cnt,
               absence_perc_newhire_turnover_cnt,
               absence_perc_average_tenure_cnt,
               absence_perc_avg_time_to_promotion_cnt,
               absence_perc_average_earnings_cnt,
               absence_perc_overtime_perc_cnt,
               db_schema,
               environment
            FROM 
                ${hiveconf:__GREEN_MAIN_DB__}.rosie_corr_hr_ind_practitioner
                --WHERE environment='${hiveconf:environment}'
             ) metric
             LATERAL VIEW stack
                          (42,
                            '76','69',turnover_rate_newhire_turnover_corr,turnover_rate_newhire_turnover_cnt,
                            '76','60',turnover_rate_average_tenure_corr,turnover_rate_average_tenure_cnt,
                            '76','79',turnover_rate_avg_time_to_promotion_corr,turnover_rate_avg_time_to_promotion_cnt,
                            '76','201',turnover_rate_average_earnings_corr,turnover_rate_average_earnings_cnt,
                            '76','2',turnover_rate_absence_perc_corr,turnover_rate_absence_perc_cnt,
                            '76','5',turnover_rate_overtime_perc_corr,turnover_rate_overtime_perc_cnt,
                            '69','76',newhire_turnover_turnover_rate_corr,newhire_turnover_turnover_rate_cnt,
                            '69','60',newhire_turnover_average_tenure_corr,newhire_turnover_average_tenure_cnt,
                            '69','79',newhire_turnover_avg_time_to_promotion_corr,newhire_turnover_avg_time_to_promotion_cnt,
                            '69','201',newhire_turnover_average_earnings_corr,newhire_turnover_average_earnings_cnt,
                            '69','2',newhire_turnover_absence_perc_corr,newhire_turnover_absence_perc_cnt,
                            '69','5',newhire_turnover_overtime_perc_corr,newhire_turnover_overtime_perc_cnt,
                            '60','76',average_tenure_turnover_rate_corr,average_tenure_turnover_rate_cnt,
                            '60','69',average_tenure_newhire_turnover_corr,average_tenure_newhire_turnover_cnt,
                            '60','79',average_tenure_avg_time_to_promotion_corr,average_tenure_avg_time_to_promotion_cnt,
                            '60','201',average_tenure_average_earnings_corr,average_tenure_average_earnings_cnt,
                            '60','2',average_tenure_absence_perc_corr,average_tenure_absence_perc_cnt,
                            '60','5',average_tenure_overtime_perc_corr,average_tenure_overtime_perc_cnt,
                            '79','76',avg_time_to_promotion_turnover_rate_corr,avg_time_to_promotion_turnover_rate_cnt,
                            '79','69',avg_time_to_promotion_newhire_turnover_corr,avg_time_to_promotion_newhire_turnover_cnt,
                            '79','60',avg_time_to_promotion_average_tenure_corr,avg_time_to_promotion_average_tenure_cnt,
                            '79','201',avg_time_to_promotion_average_earnings_corr,avg_time_to_promotion_average_earnings_cnt,
                            '79','2',avg_time_to_promotion_absence_perc_corr,avg_time_to_promotion_absence_perc_cnt,
                            '79','5',avg_time_to_promotion_overtime_perc_corr,avg_time_to_promotion_overtime_perc_cnt,
                            '201','76',average_earnings_turnover_rate_corr,average_earnings_turnover_rate_cnt,
                            '201','69',average_earnings_newhire_turnover_corr,average_earnings_newhire_turnover_cnt,
                            '201','60',average_earnings_average_tenure_corr,average_earnings_average_tenure_cnt,
                            '201','79',average_earnings_avg_time_to_promotion_corr,average_earnings_avg_time_to_promotion_cnt,
                            '201','2',average_earnings_absence_perc_corr,average_earnings_absence_perc_cnt,
                            '201','5',average_earnings_overtime_perc_corr,average_earnings_overtime_perc_cnt,
                            '5','76',overtime_perc_turnover_rate_corr,overtime_perc_turnover_rate_cnt,
                            '5','69',overtime_perc_newhire_turnover_corr,overtime_perc_newhire_turnover_cnt,
                            '5','60',overtime_perc_average_tenure_corr,overtime_perc_average_tenure_cnt,
                            '5','79',overtime_perc_avg_time_to_promotion_corr,overtime_perc_avg_time_to_promotion_cnt,
                            '5','201',overtime_perc_average_earnings_corr,overtime_perc_average_earnings_cnt,
                            '5','2',overtime_perc_absence_perc_corr,overtime_perc_absence_perc_cnt,
                            '2','76',absence_perc_turnover_rate_corr,absence_perc_turnover_rate_cnt,
                            '2','69',absence_perc_newhire_turnover_corr,absence_perc_newhire_turnover_cnt,
                            '2','60',absence_perc_average_tenure_corr,absence_perc_average_tenure_cnt,
                            '2','79',absence_perc_avg_time_to_promotion_corr,absence_perc_avg_time_to_promotion_cnt,
                            '2','201',absence_perc_average_earnings_corr,absence_perc_average_earnings_cnt,
                            '2','5',absence_perc_overtime_perc_corr,absence_perc_overtime_perc_cnt
                            ) metrics AS metric_ky_1, metric_ky_2, metric_corr,metric_cnt
    
    ) corr
    LATERAL VIEW EXPLODE(map(
            '0',array(corr_0,cnt_0),
            '1',array(corr_1,cnt_1),
            '2',array(corr_2,cnt_2))) t2 AS diff,corr_value
    WHERE corr_value[0] IS NOT NULL
    

