package com.adp.datacloud.ds.rdbms;

import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.NClob;
import java.sql.ParameterMetaData;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Map;

import org.apache.log4j.Logger;

public class CallableStatementSpy implements CallableStatement {

	private Logger logger = Logger.getLogger(CallableStatementSpy.class);

	protected CallableStatement realCallableStatement;
	private String sql;

	public CallableStatementSpy(CallableStatement realCallableStatement, String sql) {
		this.realCallableStatement = realCallableStatement;
		this.sql = sql;
	}

	/**
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#addBatch()
	 */
	@Override
	public void addBatch() throws SQLException {
		realCallableStatement.addBatch();
	}

	/**
	 * @param sql
	 * @throws SQLException
	 * @see java.sql.Statement#addBatch(java.lang.String)
	 */
	@Override
	public void addBatch(String sql) throws SQLException {
		realCallableStatement.addBatch(sql);
	}

	/**
	 * @throws SQLException
	 * @see java.sql.Statement#cancel()
	 */
	@Override
	public void cancel() throws SQLException {
		realCallableStatement.cancel();
	}

	/**
	 * @throws SQLException
	 * @see java.sql.Statement#clearBatch()
	 */
	@Override
	public void clearBatch() throws SQLException {
		realCallableStatement.clearBatch();
	}

	/**
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#clearParameters()
	 */
	@Override
	public void clearParameters() throws SQLException {
		realCallableStatement.clearParameters();
	}

	/**
	 * @throws SQLException
	 * @see java.sql.Statement#clearWarnings()
	 */
	@Override
	public void clearWarnings() throws SQLException {
		realCallableStatement.clearWarnings();
	}

	/**
	 * @throws SQLException
	 * @see java.sql.Statement#close()
	 */
	@Override
	public void close() throws SQLException {
		realCallableStatement.close();
	}

	/**
	 * @throws SQLException
	 * @see java.sql.Statement#closeOnCompletion()
	 */
	@Override
	public void closeOnCompletion() throws SQLException {
		realCallableStatement.closeOnCompletion();
	}

	/**
	 * @return
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#execute()
	 */
	@Override
	public boolean execute() throws SQLException {
		return realCallableStatement.execute();
	}

	/**
	 * @param sql
	 * @param autoGeneratedKeys
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#execute(java.lang.String, int)
	 */
	@Override
	public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
		return realCallableStatement.execute(sql, autoGeneratedKeys);
	}

	/**
	 * @param sql
	 * @param columnIndexes
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#execute(java.lang.String, int[])
	 */
	@Override
	public boolean execute(String sql, int[] columnIndexes) throws SQLException {
		return realCallableStatement.execute(sql, columnIndexes);
	}

	/**
	 * @param sql
	 * @param columnNames
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#execute(java.lang.String, java.lang.String[])
	 */
	@Override
	public boolean execute(String sql, String[] columnNames) throws SQLException {
		return realCallableStatement.execute(sql, columnNames);
	}

	/**
	 * @param sql
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#execute(java.lang.String)
	 */
	@Override
	public boolean execute(String sql) throws SQLException {
		return realCallableStatement.execute(sql);
	}

	/**
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#executeBatch()
	 */
	@Override
	public int[] executeBatch() throws SQLException {
		return realCallableStatement.executeBatch();
	}

	/**
	 * @return
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#executeQuery()
	 */
	@Override
	public ResultSet executeQuery() throws SQLException {
		long tstart = System.currentTimeMillis();
		ResultSet resultSet = realCallableStatement.executeQuery();
		logger.info(sql + " JDBC_SQL_EXEC_TIME_MS:" + (System.currentTimeMillis() - tstart));
		return resultSet;
	}

	/**
	 * @param sql
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#executeQuery(java.lang.String)
	 */
	@Override
	public ResultSet executeQuery(String sql) throws SQLException {
		long tstart = System.currentTimeMillis();
		ResultSet resultSet = realCallableStatement.executeQuery(sql);
		logger.info(sql + " JDBC_SQL_EXEC_TIME_MS:" + (System.currentTimeMillis() - tstart));
		return resultSet;
	}

	/**
	 * @return
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#executeUpdate()
	 */
	@Override
	public int executeUpdate() throws SQLException {
		long tstart = System.currentTimeMillis();
		int executeUpdate = realCallableStatement.executeUpdate();
		logger.info(sql + " JDBC_SQL_EXEC_TIME_MS:" + (System.currentTimeMillis() - tstart));
		return executeUpdate;
	}

	/**
	 * @param sql
	 * @param autoGeneratedKeys
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#executeUpdate(java.lang.String, int)
	 */
	@Override
	public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
		long tstart = System.currentTimeMillis();
		int executeUpdate = realCallableStatement.executeUpdate(sql);
		logger.info(sql + " JDBC_SQL_EXEC_TIME_MS:" + (System.currentTimeMillis() - tstart));
		return executeUpdate;
	}

	/**
	 * @param sql
	 * @param columnIndexes
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#executeUpdate(java.lang.String, int[])
	 */
	@Override
	public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
		return realCallableStatement.executeUpdate(sql, columnIndexes);
	}

	/**
	 * @param sql
	 * @param columnNames
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#executeUpdate(java.lang.String, java.lang.String[])
	 */
	@Override
	public int executeUpdate(String sql, String[] columnNames) throws SQLException {
		return realCallableStatement.executeUpdate(sql, columnNames);
	}

	/**
	 * @param sql
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#executeUpdate(java.lang.String)
	 */
	@Override
	public int executeUpdate(String sql) throws SQLException {
		return realCallableStatement.executeUpdate(sql);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getArray(int)
	 */
	@Override
	public Array getArray(int arg0) throws SQLException {
		return realCallableStatement.getArray(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getArray(java.lang.String)
	 */
	@Override
	public Array getArray(String arg0) throws SQLException {
		return realCallableStatement.getArray(arg0);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @return
	 * @throws SQLException
	 * @deprecated
	 * @see java.sql.CallableStatement#getBigDecimal(int, int)
	 */
	@Deprecated
	@Override
	public BigDecimal getBigDecimal(int arg0, int arg1) throws SQLException {
		return realCallableStatement.getBigDecimal(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getBigDecimal(int)
	 */
	@Override
	public BigDecimal getBigDecimal(int arg0) throws SQLException {
		return realCallableStatement.getBigDecimal(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getBigDecimal(java.lang.String)
	 */
	@Override
	public BigDecimal getBigDecimal(String arg0) throws SQLException {
		return realCallableStatement.getBigDecimal(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getBlob(int)
	 */
	@Override
	public Blob getBlob(int arg0) throws SQLException {
		return realCallableStatement.getBlob(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getBlob(java.lang.String)
	 */
	@Override
	public Blob getBlob(String arg0) throws SQLException {
		return realCallableStatement.getBlob(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getBoolean(int)
	 */
	@Override
	public boolean getBoolean(int arg0) throws SQLException {
		return realCallableStatement.getBoolean(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getBoolean(java.lang.String)
	 */
	@Override
	public boolean getBoolean(String arg0) throws SQLException {
		return realCallableStatement.getBoolean(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getByte(int)
	 */
	@Override
	public byte getByte(int arg0) throws SQLException {
		return realCallableStatement.getByte(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getByte(java.lang.String)
	 */
	@Override
	public byte getByte(String arg0) throws SQLException {
		return realCallableStatement.getByte(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getBytes(int)
	 */
	@Override
	public byte[] getBytes(int arg0) throws SQLException {
		return realCallableStatement.getBytes(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getBytes(java.lang.String)
	 */
	@Override
	public byte[] getBytes(String arg0) throws SQLException {
		return realCallableStatement.getBytes(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getCharacterStream(int)
	 */
	@Override
	public Reader getCharacterStream(int arg0) throws SQLException {
		return realCallableStatement.getCharacterStream(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getCharacterStream(java.lang.String)
	 */
	@Override
	public Reader getCharacterStream(String arg0) throws SQLException {
		return realCallableStatement.getCharacterStream(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getClob(int)
	 */
	@Override
	public Clob getClob(int arg0) throws SQLException {
		return realCallableStatement.getClob(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getClob(java.lang.String)
	 */
	@Override
	public Clob getClob(String arg0) throws SQLException {
		return realCallableStatement.getClob(arg0);
	}

	/**
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#getConnection()
	 */
	@Override
	public Connection getConnection() throws SQLException {
		return realCallableStatement.getConnection();
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getDate(int, java.util.Calendar)
	 */
	@Override
	public Date getDate(int arg0, Calendar arg1) throws SQLException {
		return realCallableStatement.getDate(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getDate(int)
	 */
	@Override
	public Date getDate(int arg0) throws SQLException {
		return realCallableStatement.getDate(arg0);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getDate(java.lang.String, java.util.Calendar)
	 */
	@Override
	public Date getDate(String arg0, Calendar arg1) throws SQLException {
		return realCallableStatement.getDate(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getDate(java.lang.String)
	 */
	@Override
	public Date getDate(String arg0) throws SQLException {
		return realCallableStatement.getDate(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getDouble(int)
	 */
	@Override
	public double getDouble(int arg0) throws SQLException {
		return realCallableStatement.getDouble(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getDouble(java.lang.String)
	 */
	@Override
	public double getDouble(String arg0) throws SQLException {
		return realCallableStatement.getDouble(arg0);
	}

	/**
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#getFetchDirection()
	 */
	@Override
	public int getFetchDirection() throws SQLException {
		return realCallableStatement.getFetchDirection();
	}

	/**
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#getFetchSize()
	 */
	@Override
	public int getFetchSize() throws SQLException {
		return realCallableStatement.getFetchSize();
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getFloat(int)
	 */
	@Override
	public float getFloat(int arg0) throws SQLException {
		return realCallableStatement.getFloat(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getFloat(java.lang.String)
	 */
	@Override
	public float getFloat(String arg0) throws SQLException {
		return realCallableStatement.getFloat(arg0);
	}

	/**
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#getGeneratedKeys()
	 */
	@Override
	public ResultSet getGeneratedKeys() throws SQLException {
		return realCallableStatement.getGeneratedKeys();
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getInt(int)
	 */
	@Override
	public int getInt(int arg0) throws SQLException {
		return realCallableStatement.getInt(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getInt(java.lang.String)
	 */
	@Override
	public int getInt(String arg0) throws SQLException {
		return realCallableStatement.getInt(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getLong(int)
	 */
	@Override
	public long getLong(int arg0) throws SQLException {
		return realCallableStatement.getLong(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getLong(java.lang.String)
	 */
	@Override
	public long getLong(String arg0) throws SQLException {
		return realCallableStatement.getLong(arg0);
	}

	/**
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#getMaxFieldSize()
	 */
	@Override
	public int getMaxFieldSize() throws SQLException {
		return realCallableStatement.getMaxFieldSize();
	}

	/**
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#getMaxRows()
	 */
	@Override
	public int getMaxRows() throws SQLException {
		return realCallableStatement.getMaxRows();
	}

	/**
	 * @return
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#getMetaData()
	 */
	@Override
	public ResultSetMetaData getMetaData() throws SQLException {
		return realCallableStatement.getMetaData();
	}

	/**
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#getMoreResults()
	 */
	@Override
	public boolean getMoreResults() throws SQLException {
		return realCallableStatement.getMoreResults();
	}

	/**
	 * @param current
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#getMoreResults(int)
	 */
	@Override
	public boolean getMoreResults(int current) throws SQLException {
		return realCallableStatement.getMoreResults(current);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getNCharacterStream(int)
	 */
	@Override
	public Reader getNCharacterStream(int arg0) throws SQLException {
		return realCallableStatement.getNCharacterStream(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getNCharacterStream(java.lang.String)
	 */
	@Override
	public Reader getNCharacterStream(String arg0) throws SQLException {
		return realCallableStatement.getNCharacterStream(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getNClob(int)
	 */
	@Override
	public NClob getNClob(int arg0) throws SQLException {
		return realCallableStatement.getNClob(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getNClob(java.lang.String)
	 */
	@Override
	public NClob getNClob(String arg0) throws SQLException {
		return realCallableStatement.getNClob(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getNString(int)
	 */
	@Override
	public String getNString(int arg0) throws SQLException {
		return realCallableStatement.getNString(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getNString(java.lang.String)
	 */
	@Override
	public String getNString(String arg0) throws SQLException {
		return realCallableStatement.getNString(arg0);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getObject(int, java.lang.Class)
	 */
	@Override
	public <T> T getObject(int arg0, Class<T> arg1) throws SQLException {
		return realCallableStatement.getObject(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getObject(int, java.util.Map)
	 */
	@Override
	public Object getObject(int arg0, Map<String, Class<?>> arg1) throws SQLException {
		return realCallableStatement.getObject(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getObject(int)
	 */
	@Override
	public Object getObject(int arg0) throws SQLException {
		return realCallableStatement.getObject(arg0);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getObject(java.lang.String, java.lang.Class)
	 */
	@Override
	public <T> T getObject(String arg0, Class<T> arg1) throws SQLException {
		return realCallableStatement.getObject(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getObject(java.lang.String, java.util.Map)
	 */
	@Override
	public Object getObject(String arg0, Map<String, Class<?>> arg1) throws SQLException {
		return realCallableStatement.getObject(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getObject(java.lang.String)
	 */
	@Override
	public Object getObject(String arg0) throws SQLException {
		return realCallableStatement.getObject(arg0);
	}

	/**
	 * @return
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#getParameterMetaData()
	 */
	@Override
	public ParameterMetaData getParameterMetaData() throws SQLException {
		return realCallableStatement.getParameterMetaData();
	}

	/**
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#getQueryTimeout()
	 */
	@Override
	public int getQueryTimeout() throws SQLException {
		return realCallableStatement.getQueryTimeout();
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getRef(int)
	 */
	@Override
	public Ref getRef(int arg0) throws SQLException {
		return realCallableStatement.getRef(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getRef(java.lang.String)
	 */
	@Override
	public Ref getRef(String arg0) throws SQLException {
		return realCallableStatement.getRef(arg0);
	}

	/**
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#getResultSet()
	 */
	@Override
	public ResultSet getResultSet() throws SQLException {
		return realCallableStatement.getResultSet();
	}

	/**
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#getResultSetConcurrency()
	 */
	@Override
	public int getResultSetConcurrency() throws SQLException {
		return realCallableStatement.getResultSetConcurrency();
	}

	/**
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#getResultSetHoldability()
	 */
	@Override
	public int getResultSetHoldability() throws SQLException {
		return realCallableStatement.getResultSetHoldability();
	}

	/**
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#getResultSetType()
	 */
	@Override
	public int getResultSetType() throws SQLException {
		return realCallableStatement.getResultSetType();
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getRowId(int)
	 */
	@Override
	public RowId getRowId(int arg0) throws SQLException {
		return realCallableStatement.getRowId(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getRowId(java.lang.String)
	 */
	@Override
	public RowId getRowId(String arg0) throws SQLException {
		return realCallableStatement.getRowId(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getSQLXML(int)
	 */
	@Override
	public SQLXML getSQLXML(int arg0) throws SQLException {
		return realCallableStatement.getSQLXML(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getSQLXML(java.lang.String)
	 */
	@Override
	public SQLXML getSQLXML(String arg0) throws SQLException {
		return realCallableStatement.getSQLXML(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getShort(int)
	 */
	@Override
	public short getShort(int arg0) throws SQLException {
		return realCallableStatement.getShort(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getShort(java.lang.String)
	 */
	@Override
	public short getShort(String arg0) throws SQLException {
		return realCallableStatement.getShort(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getString(int)
	 */
	@Override
	public String getString(int arg0) throws SQLException {
		return realCallableStatement.getString(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getString(java.lang.String)
	 */
	@Override
	public String getString(String arg0) throws SQLException {
		return realCallableStatement.getString(arg0);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getTime(int, java.util.Calendar)
	 */
	@Override
	public Time getTime(int arg0, Calendar arg1) throws SQLException {
		return realCallableStatement.getTime(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getTime(int)
	 */
	@Override
	public Time getTime(int arg0) throws SQLException {
		return realCallableStatement.getTime(arg0);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getTime(java.lang.String, java.util.Calendar)
	 */
	@Override
	public Time getTime(String arg0, Calendar arg1) throws SQLException {
		return realCallableStatement.getTime(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getTime(java.lang.String)
	 */
	@Override
	public Time getTime(String arg0) throws SQLException {
		return realCallableStatement.getTime(arg0);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getTimestamp(int, java.util.Calendar)
	 */
	@Override
	public Timestamp getTimestamp(int arg0, Calendar arg1) throws SQLException {
		return realCallableStatement.getTimestamp(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getTimestamp(int)
	 */
	@Override
	public Timestamp getTimestamp(int arg0) throws SQLException {
		return realCallableStatement.getTimestamp(arg0);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getTimestamp(java.lang.String,
	 *      java.util.Calendar)
	 */
	@Override
	public Timestamp getTimestamp(String arg0, Calendar arg1) throws SQLException {
		return realCallableStatement.getTimestamp(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getTimestamp(java.lang.String)
	 */
	@Override
	public Timestamp getTimestamp(String arg0) throws SQLException {
		return realCallableStatement.getTimestamp(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getURL(int)
	 */
	@Override
	public URL getURL(int arg0) throws SQLException {
		return realCallableStatement.getURL(arg0);
	}

	/**
	 * @param arg0
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#getURL(java.lang.String)
	 */
	@Override
	public URL getURL(String arg0) throws SQLException {
		return realCallableStatement.getURL(arg0);
	}

	/**
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#getUpdateCount()
	 */
	@Override
	public int getUpdateCount() throws SQLException {
		return realCallableStatement.getUpdateCount();
	}

	/**
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#getWarnings()
	 */
	@Override
	public SQLWarning getWarnings() throws SQLException {
		return realCallableStatement.getWarnings();
	}

	/**
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#isCloseOnCompletion()
	 */
	@Override
	public boolean isCloseOnCompletion() throws SQLException {
		return realCallableStatement.isCloseOnCompletion();
	}

	/**
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#isClosed()
	 */
	@Override
	public boolean isClosed() throws SQLException {
		return realCallableStatement.isClosed();
	}

	/**
	 * @return
	 * @throws SQLException
	 * @see java.sql.Statement#isPoolable()
	 */
	@Override
	public boolean isPoolable() throws SQLException {
		return realCallableStatement.isPoolable();
	}

	/**
	 * @param iface
	 * @return
	 * @throws SQLException
	 * @see java.sql.Wrapper#isWrapperFor(java.lang.Class)
	 */
	@Override
	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		return realCallableStatement.isWrapperFor(iface);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.CallableStatement#registerOutParameter(int, int, int)
	 */
	@Override
	public void registerOutParameter(int arg0, int arg1, int arg2) throws SQLException {
		realCallableStatement.registerOutParameter(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.CallableStatement#registerOutParameter(int, int,
	 *      java.lang.String)
	 */
	@Override
	public void registerOutParameter(int arg0, int arg1, String arg2) throws SQLException {
		realCallableStatement.registerOutParameter(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#registerOutParameter(int, int)
	 */
	@Override
	public void registerOutParameter(int arg0, int arg1) throws SQLException {
		realCallableStatement.registerOutParameter(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.CallableStatement#registerOutParameter(java.lang.String, int,
	 *      int)
	 */
	@Override
	public void registerOutParameter(String arg0, int arg1, int arg2) throws SQLException {
		realCallableStatement.registerOutParameter(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.CallableStatement#registerOutParameter(java.lang.String, int,
	 *      java.lang.String)
	 */
	@Override
	public void registerOutParameter(String arg0, int arg1, String arg2) throws SQLException {
		realCallableStatement.registerOutParameter(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#registerOutParameter(java.lang.String, int)
	 */
	@Override
	public void registerOutParameter(String arg0, int arg1) throws SQLException {
		realCallableStatement.registerOutParameter(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setArray(int, java.sql.Array)
	 */
	@Override
	public void setArray(int arg0, Array arg1) throws SQLException {
		realCallableStatement.setArray(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setAsciiStream(int, java.io.InputStream, int)
	 */
	@Override
	public void setAsciiStream(int arg0, InputStream arg1, int arg2) throws SQLException {
		realCallableStatement.setAsciiStream(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setAsciiStream(int, java.io.InputStream,
	 *      long)
	 */
	@Override
	public void setAsciiStream(int arg0, InputStream arg1, long arg2) throws SQLException {
		realCallableStatement.setAsciiStream(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setAsciiStream(int, java.io.InputStream)
	 */
	@Override
	public void setAsciiStream(int arg0, InputStream arg1) throws SQLException {
		realCallableStatement.setAsciiStream(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setAsciiStream(java.lang.String,
	 *      java.io.InputStream, int)
	 */
	@Override
	public void setAsciiStream(String arg0, InputStream arg1, int arg2) throws SQLException {
		realCallableStatement.setAsciiStream(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setAsciiStream(java.lang.String,
	 *      java.io.InputStream, long)
	 */
	@Override
	public void setAsciiStream(String arg0, InputStream arg1, long arg2) throws SQLException {
		realCallableStatement.setAsciiStream(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setAsciiStream(java.lang.String,
	 *      java.io.InputStream)
	 */
	@Override
	public void setAsciiStream(String arg0, InputStream arg1) throws SQLException {
		realCallableStatement.setAsciiStream(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setBigDecimal(int, java.math.BigDecimal)
	 */
	@Override
	public void setBigDecimal(int arg0, BigDecimal arg1) throws SQLException {
		realCallableStatement.setBigDecimal(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setBigDecimal(java.lang.String,
	 *      java.math.BigDecimal)
	 */
	@Override
	public void setBigDecimal(String arg0, BigDecimal arg1) throws SQLException {
		realCallableStatement.setBigDecimal(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setBinaryStream(int, java.io.InputStream,
	 *      int)
	 */
	@Override
	public void setBinaryStream(int arg0, InputStream arg1, int arg2) throws SQLException {
		realCallableStatement.setBinaryStream(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setBinaryStream(int, java.io.InputStream,
	 *      long)
	 */
	@Override
	public void setBinaryStream(int arg0, InputStream arg1, long arg2) throws SQLException {
		realCallableStatement.setBinaryStream(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setBinaryStream(int, java.io.InputStream)
	 */
	@Override
	public void setBinaryStream(int arg0, InputStream arg1) throws SQLException {
		realCallableStatement.setBinaryStream(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setBinaryStream(java.lang.String,
	 *      java.io.InputStream, int)
	 */
	@Override
	public void setBinaryStream(String arg0, InputStream arg1, int arg2) throws SQLException {
		realCallableStatement.setBinaryStream(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setBinaryStream(java.lang.String,
	 *      java.io.InputStream, long)
	 */
	@Override
	public void setBinaryStream(String arg0, InputStream arg1, long arg2) throws SQLException {
		realCallableStatement.setBinaryStream(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setBinaryStream(java.lang.String,
	 *      java.io.InputStream)
	 */
	@Override
	public void setBinaryStream(String arg0, InputStream arg1) throws SQLException {
		realCallableStatement.setBinaryStream(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setBlob(int, java.sql.Blob)
	 */
	@Override
	public void setBlob(int arg0, Blob arg1) throws SQLException {
		realCallableStatement.setBlob(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setBlob(int, java.io.InputStream, long)
	 */
	@Override
	public void setBlob(int arg0, InputStream arg1, long arg2) throws SQLException {
		realCallableStatement.setBlob(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setBlob(int, java.io.InputStream)
	 */
	@Override
	public void setBlob(int arg0, InputStream arg1) throws SQLException {
		realCallableStatement.setBlob(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setBlob(java.lang.String, java.sql.Blob)
	 */
	@Override
	public void setBlob(String arg0, Blob arg1) throws SQLException {
		realCallableStatement.setBlob(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setBlob(java.lang.String,
	 *      java.io.InputStream, long)
	 */
	@Override
	public void setBlob(String arg0, InputStream arg1, long arg2) throws SQLException {
		realCallableStatement.setBlob(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setBlob(java.lang.String,
	 *      java.io.InputStream)
	 */
	@Override
	public void setBlob(String arg0, InputStream arg1) throws SQLException {
		realCallableStatement.setBlob(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setBoolean(int, boolean)
	 */
	@Override
	public void setBoolean(int arg0, boolean arg1) throws SQLException {
		realCallableStatement.setBoolean(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setBoolean(java.lang.String, boolean)
	 */
	@Override
	public void setBoolean(String arg0, boolean arg1) throws SQLException {
		realCallableStatement.setBoolean(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setByte(int, byte)
	 */
	@Override
	public void setByte(int arg0, byte arg1) throws SQLException {
		realCallableStatement.setByte(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setByte(java.lang.String, byte)
	 */
	@Override
	public void setByte(String arg0, byte arg1) throws SQLException {
		realCallableStatement.setByte(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setBytes(int, byte[])
	 */
	@Override
	public void setBytes(int arg0, byte[] arg1) throws SQLException {
		realCallableStatement.setBytes(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setBytes(java.lang.String, byte[])
	 */
	@Override
	public void setBytes(String arg0, byte[] arg1) throws SQLException {
		realCallableStatement.setBytes(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setCharacterStream(int, java.io.Reader, int)
	 */
	@Override
	public void setCharacterStream(int arg0, Reader arg1, int arg2) throws SQLException {
		realCallableStatement.setCharacterStream(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setCharacterStream(int, java.io.Reader, long)
	 */
	@Override
	public void setCharacterStream(int arg0, Reader arg1, long arg2) throws SQLException {
		realCallableStatement.setCharacterStream(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setCharacterStream(int, java.io.Reader)
	 */
	@Override
	public void setCharacterStream(int arg0, Reader arg1) throws SQLException {
		realCallableStatement.setCharacterStream(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setCharacterStream(java.lang.String,
	 *      java.io.Reader, int)
	 */
	@Override
	public void setCharacterStream(String arg0, Reader arg1, int arg2) throws SQLException {
		realCallableStatement.setCharacterStream(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setCharacterStream(java.lang.String,
	 *      java.io.Reader, long)
	 */
	@Override
	public void setCharacterStream(String arg0, Reader arg1, long arg2) throws SQLException {
		realCallableStatement.setCharacterStream(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setCharacterStream(java.lang.String,
	 *      java.io.Reader)
	 */
	@Override
	public void setCharacterStream(String arg0, Reader arg1) throws SQLException {
		realCallableStatement.setCharacterStream(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setClob(int, java.sql.Clob)
	 */
	@Override
	public void setClob(int arg0, Clob arg1) throws SQLException {
		realCallableStatement.setClob(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setClob(int, java.io.Reader, long)
	 */
	@Override
	public void setClob(int arg0, Reader arg1, long arg2) throws SQLException {
		realCallableStatement.setClob(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setClob(int, java.io.Reader)
	 */
	@Override
	public void setClob(int arg0, Reader arg1) throws SQLException {
		realCallableStatement.setClob(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setClob(java.lang.String, java.sql.Clob)
	 */
	@Override
	public void setClob(String arg0, Clob arg1) throws SQLException {
		realCallableStatement.setClob(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setClob(java.lang.String, java.io.Reader,
	 *      long)
	 */
	@Override
	public void setClob(String arg0, Reader arg1, long arg2) throws SQLException {
		realCallableStatement.setClob(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setClob(java.lang.String, java.io.Reader)
	 */
	@Override
	public void setClob(String arg0, Reader arg1) throws SQLException {
		realCallableStatement.setClob(arg0, arg1);
	}

	/**
	 * @param name
	 * @throws SQLException
	 * @see java.sql.Statement#setCursorName(java.lang.String)
	 */
	@Override
	public void setCursorName(String name) throws SQLException {
		realCallableStatement.setCursorName(name);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setDate(int, java.sql.Date,
	 *      java.util.Calendar)
	 */
	@Override
	public void setDate(int arg0, Date arg1, Calendar arg2) throws SQLException {
		realCallableStatement.setDate(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setDate(int, java.sql.Date)
	 */
	@Override
	public void setDate(int arg0, Date arg1) throws SQLException {
		realCallableStatement.setDate(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setDate(java.lang.String, java.sql.Date,
	 *      java.util.Calendar)
	 */
	@Override
	public void setDate(String arg0, Date arg1, Calendar arg2) throws SQLException {
		realCallableStatement.setDate(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setDate(java.lang.String, java.sql.Date)
	 */
	@Override
	public void setDate(String arg0, Date arg1) throws SQLException {
		realCallableStatement.setDate(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setDouble(int, double)
	 */
	@Override
	public void setDouble(int arg0, double arg1) throws SQLException {
		realCallableStatement.setDouble(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setDouble(java.lang.String, double)
	 */
	@Override
	public void setDouble(String arg0, double arg1) throws SQLException {
		realCallableStatement.setDouble(arg0, arg1);
	}

	/**
	 * @param enable
	 * @throws SQLException
	 * @see java.sql.Statement#setEscapeProcessing(boolean)
	 */
	@Override
	public void setEscapeProcessing(boolean enable) throws SQLException {
		realCallableStatement.setEscapeProcessing(enable);
	}

	/**
	 * @param direction
	 * @throws SQLException
	 * @see java.sql.Statement#setFetchDirection(int)
	 */
	@Override
	public void setFetchDirection(int direction) throws SQLException {
		realCallableStatement.setFetchDirection(direction);
	}

	/**
	 * @param rows
	 * @throws SQLException
	 * @see java.sql.Statement#setFetchSize(int)
	 */
	@Override
	public void setFetchSize(int rows) throws SQLException {
		realCallableStatement.setFetchSize(rows);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setFloat(int, float)
	 */
	@Override
	public void setFloat(int arg0, float arg1) throws SQLException {
		realCallableStatement.setFloat(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setFloat(java.lang.String, float)
	 */
	@Override
	public void setFloat(String arg0, float arg1) throws SQLException {
		realCallableStatement.setFloat(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setInt(int, int)
	 */
	@Override
	public void setInt(int arg0, int arg1) throws SQLException {
		realCallableStatement.setInt(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setInt(java.lang.String, int)
	 */
	@Override
	public void setInt(String arg0, int arg1) throws SQLException {
		realCallableStatement.setInt(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setLong(int, long)
	 */
	@Override
	public void setLong(int arg0, long arg1) throws SQLException {
		realCallableStatement.setLong(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setLong(java.lang.String, long)
	 */
	@Override
	public void setLong(String arg0, long arg1) throws SQLException {
		realCallableStatement.setLong(arg0, arg1);
	}

	/**
	 * @param max
	 * @throws SQLException
	 * @see java.sql.Statement#setMaxFieldSize(int)
	 */
	@Override
	public void setMaxFieldSize(int max) throws SQLException {
		realCallableStatement.setMaxFieldSize(max);
	}

	/**
	 * @param max
	 * @throws SQLException
	 * @see java.sql.Statement#setMaxRows(int)
	 */
	@Override
	public void setMaxRows(int max) throws SQLException {
		realCallableStatement.setMaxRows(max);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setNCharacterStream(int, java.io.Reader,
	 *      long)
	 */
	@Override
	public void setNCharacterStream(int arg0, Reader arg1, long arg2) throws SQLException {
		realCallableStatement.setNCharacterStream(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setNCharacterStream(int, java.io.Reader)
	 */
	@Override
	public void setNCharacterStream(int arg0, Reader arg1) throws SQLException {
		realCallableStatement.setNCharacterStream(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setNCharacterStream(java.lang.String,
	 *      java.io.Reader, long)
	 */
	@Override
	public void setNCharacterStream(String arg0, Reader arg1, long arg2) throws SQLException {
		realCallableStatement.setNCharacterStream(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setNCharacterStream(java.lang.String,
	 *      java.io.Reader)
	 */
	@Override
	public void setNCharacterStream(String arg0, Reader arg1) throws SQLException {
		realCallableStatement.setNCharacterStream(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setNClob(int, java.sql.NClob)
	 */
	@Override
	public void setNClob(int arg0, NClob arg1) throws SQLException {
		realCallableStatement.setNClob(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setNClob(int, java.io.Reader, long)
	 */
	@Override
	public void setNClob(int arg0, Reader arg1, long arg2) throws SQLException {
		realCallableStatement.setNClob(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setNClob(int, java.io.Reader)
	 */
	@Override
	public void setNClob(int arg0, Reader arg1) throws SQLException {
		realCallableStatement.setNClob(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setNClob(java.lang.String, java.sql.NClob)
	 */
	@Override
	public void setNClob(String arg0, NClob arg1) throws SQLException {
		realCallableStatement.setNClob(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setNClob(java.lang.String, java.io.Reader,
	 *      long)
	 */
	@Override
	public void setNClob(String arg0, Reader arg1, long arg2) throws SQLException {
		realCallableStatement.setNClob(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setNClob(java.lang.String, java.io.Reader)
	 */
	@Override
	public void setNClob(String arg0, Reader arg1) throws SQLException {
		realCallableStatement.setNClob(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setNString(int, java.lang.String)
	 */
	@Override
	public void setNString(int arg0, String arg1) throws SQLException {
		realCallableStatement.setNString(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setNString(java.lang.String,
	 *      java.lang.String)
	 */
	@Override
	public void setNString(String arg0, String arg1) throws SQLException {
		realCallableStatement.setNString(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setNull(int, int, java.lang.String)
	 */
	@Override
	public void setNull(int arg0, int arg1, String arg2) throws SQLException {
		realCallableStatement.setNull(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setNull(int, int)
	 */
	@Override
	public void setNull(int arg0, int arg1) throws SQLException {
		realCallableStatement.setNull(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setNull(java.lang.String, int,
	 *      java.lang.String)
	 */
	@Override
	public void setNull(String arg0, int arg1, String arg2) throws SQLException {
		realCallableStatement.setNull(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setNull(java.lang.String, int)
	 */
	@Override
	public void setNull(String arg0, int arg1) throws SQLException {
		realCallableStatement.setNull(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @param arg3
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setObject(int, java.lang.Object, int, int)
	 */
	@Override
	public void setObject(int arg0, Object arg1, int arg2, int arg3) throws SQLException {
		realCallableStatement.setObject(arg0, arg1, arg2, arg3);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setObject(int, java.lang.Object, int)
	 */
	@Override
	public void setObject(int arg0, Object arg1, int arg2) throws SQLException {
		realCallableStatement.setObject(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setObject(int, java.lang.Object)
	 */
	@Override
	public void setObject(int arg0, Object arg1) throws SQLException {
		realCallableStatement.setObject(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @param arg3
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setObject(java.lang.String, java.lang.Object,
	 *      int, int)
	 */
	@Override
	public void setObject(String arg0, Object arg1, int arg2, int arg3) throws SQLException {
		realCallableStatement.setObject(arg0, arg1, arg2, arg3);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setObject(java.lang.String, java.lang.Object,
	 *      int)
	 */
	@Override
	public void setObject(String arg0, Object arg1, int arg2) throws SQLException {
		realCallableStatement.setObject(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setObject(java.lang.String, java.lang.Object)
	 */
	@Override
	public void setObject(String arg0, Object arg1) throws SQLException {
		realCallableStatement.setObject(arg0, arg1);
	}

	/**
	 * @param poolable
	 * @throws SQLException
	 * @see java.sql.Statement#setPoolable(boolean)
	 */
	@Override
	public void setPoolable(boolean poolable) throws SQLException {
		realCallableStatement.setPoolable(poolable);
	}

	/**
	 * @param seconds
	 * @throws SQLException
	 * @see java.sql.Statement#setQueryTimeout(int)
	 */
	@Override
	public void setQueryTimeout(int seconds) throws SQLException {
		realCallableStatement.setQueryTimeout(seconds);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setRef(int, java.sql.Ref)
	 */
	@Override
	public void setRef(int arg0, Ref arg1) throws SQLException {
		realCallableStatement.setRef(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setRowId(int, java.sql.RowId)
	 */
	@Override
	public void setRowId(int arg0, RowId arg1) throws SQLException {
		realCallableStatement.setRowId(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setRowId(java.lang.String, java.sql.RowId)
	 */
	@Override
	public void setRowId(String arg0, RowId arg1) throws SQLException {
		realCallableStatement.setRowId(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setSQLXML(int, java.sql.SQLXML)
	 */
	@Override
	public void setSQLXML(int arg0, SQLXML arg1) throws SQLException {
		realCallableStatement.setSQLXML(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setSQLXML(java.lang.String, java.sql.SQLXML)
	 */
	@Override
	public void setSQLXML(String arg0, SQLXML arg1) throws SQLException {
		realCallableStatement.setSQLXML(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setShort(int, short)
	 */
	@Override
	public void setShort(int arg0, short arg1) throws SQLException {
		realCallableStatement.setShort(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setShort(java.lang.String, short)
	 */
	@Override
	public void setShort(String arg0, short arg1) throws SQLException {
		realCallableStatement.setShort(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setString(int, java.lang.String)
	 */
	@Override
	public void setString(int arg0, String arg1) throws SQLException {
		realCallableStatement.setString(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setString(java.lang.String, java.lang.String)
	 */
	@Override
	public void setString(String arg0, String arg1) throws SQLException {
		realCallableStatement.setString(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setTime(int, java.sql.Time,
	 *      java.util.Calendar)
	 */
	@Override
	public void setTime(int arg0, Time arg1, Calendar arg2) throws SQLException {
		realCallableStatement.setTime(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setTime(int, java.sql.Time)
	 */
	@Override
	public void setTime(int arg0, Time arg1) throws SQLException {
		realCallableStatement.setTime(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setTime(java.lang.String, java.sql.Time,
	 *      java.util.Calendar)
	 */
	@Override
	public void setTime(String arg0, Time arg1, Calendar arg2) throws SQLException {
		realCallableStatement.setTime(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setTime(java.lang.String, java.sql.Time)
	 */
	@Override
	public void setTime(String arg0, Time arg1) throws SQLException {
		realCallableStatement.setTime(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setTimestamp(int, java.sql.Timestamp,
	 *      java.util.Calendar)
	 */
	@Override
	public void setTimestamp(int arg0, Timestamp arg1, Calendar arg2) throws SQLException {
		realCallableStatement.setTimestamp(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setTimestamp(int, java.sql.Timestamp)
	 */
	@Override
	public void setTimestamp(int arg0, Timestamp arg1) throws SQLException {
		realCallableStatement.setTimestamp(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setTimestamp(java.lang.String,
	 *      java.sql.Timestamp, java.util.Calendar)
	 */
	@Override
	public void setTimestamp(String arg0, Timestamp arg1, Calendar arg2) throws SQLException {
		realCallableStatement.setTimestamp(arg0, arg1, arg2);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setTimestamp(java.lang.String,
	 *      java.sql.Timestamp)
	 */
	@Override
	public void setTimestamp(String arg0, Timestamp arg1) throws SQLException {
		realCallableStatement.setTimestamp(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.PreparedStatement#setURL(int, java.net.URL)
	 */
	@Override
	public void setURL(int arg0, URL arg1) throws SQLException {
		realCallableStatement.setURL(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @throws SQLException
	 * @see java.sql.CallableStatement#setURL(java.lang.String, java.net.URL)
	 */
	@Override
	public void setURL(String arg0, URL arg1) throws SQLException {
		realCallableStatement.setURL(arg0, arg1);
	}

	/**
	 * @param arg0
	 * @param arg1
	 * @param arg2
	 * @throws SQLException
	 * @deprecated
	 * @see java.sql.PreparedStatement#setUnicodeStream(int, java.io.InputStream,
	 *      int)
	 */
	@Deprecated
	@Override
	public void setUnicodeStream(int arg0, InputStream arg1, int arg2) throws SQLException {
		realCallableStatement.setUnicodeStream(arg0, arg1, arg2);
	}

	/**
	 * @param iface
	 * @return
	 * @throws SQLException
	 * @see java.sql.Wrapper#unwrap(java.lang.Class)
	 */
	@Override
	public <T> T unwrap(Class<T> iface) throws SQLException {
		return realCallableStatement.unwrap(iface);
	}

	/**
	 * @return
	 * @throws SQLException
	 * @see java.sql.CallableStatement#wasNull()
	 */
	@Override
	public boolean wasNull() throws SQLException {
		return realCallableStatement.wasNull();
	}

}
