SELECT
    a.iid,
    person_id,
    last_name AS last_name_hash,
    first_name AS first_name_hash,
    middle_name AS middle_name_hash,
    preferred_name AS preferred_name_hash,
    COALESCE(Convert(Varchar(25), DOB,112) ,'')  AS dob_hash,
    DOB as dob_orig_hash,
    year(dob) AS birth_year,
    gender,
    ssn_nb AS ssn_nb_hash,
    ssn_canada AS ssn_canada_hash,
    other_last_name,
    hosp_code,
    hosp_name,
    doctor,
    blood_donor,
    advanced_directive,
    birthplace AS birthplace_hash,
    salutation,
    prefix_code,
    prefix_desc,
    suffix,
    initials,
    marital_stat_code,
    marital_stat_desc,
    eeo_code AS eeo_code_hash,
    eeo_desc AS eeo_desc_hash,
    citizenship_code,
    citizenship_desc,
    date_citizenship AS date_citizenship_hash,
    email_personal AS email_personal_hash,
    disabled,
    disabled_comments,
    dateofdeath,
    phonetic_last_name AS phonetic_last_name_hash,
    tin_nb AS tin_nb_hash,
    mobile_tel_no AS mobile_tel_no_hash,
    pager_no AS pager_no_hash,
    pager_pin_no AS pager_pin_no_hash,
    photopath,
    work_phone_1 AS work_phone_1_hash,
    work_phone_2 AS work_phone_2_hash,
    work_phone_1_ext AS work_phone_1_ext_hash,
    work_phone_2_ext AS work_phone_2_ext_hash,
    work_fax AS work_fax_hash,
    email_work AS email_work_hash,
    email_other AS email_other_hash,
    mail_stop AS mail_stop_hash,
    text1,
    text2,
    text3,
    text4,
    text5,
    text6,
    text7,
    text8,
    date1,
    date2,
    date3,
    date4,
    date5,
    date6,
    number1,
    number2,
    number3,
    number4,
    number5,
    number6,
    option1,
    option2,
    option3,
    option4,
    memo,
    last_updated_by as last_updated_by_hash,
    last_updated_date,
    deleteflag,
    last_history_code,
    last_history_date,
    adp_user_id,
    vet_disc_rel_date,
    vet_vietnam,
    vet_disabled,
    vet_other,
    profile_update_date,
    ss_ind,
    notification_email,
    person_guid,
    synch_gen_no,
    synch_updated_date,
    company_name_1099 AS company_name_1099_hash,
    display_name AS display_name_hash,
    person_advice_msg AS person_advice_msg_hash,
    alternate_name AS alternate_name_hash,
    aoid,
    time_zone,
    paperless_paystatements_ind,
    paystatements_email_notification_ind,
    eeo_verified_by AS eeo_verified_by_hash,
    text9,
    text10,
    paperless_taxstatements_ind,
    taxstatements_email_notification_ind,
    '[BATCHNUMBER]' batch_number,
    format(DATEADD(day, -1,'&PARTITION_YYYYMMDD'),'yyyyMMdd') as ingest_day,
    '[OWNERID]' AS db_schema_hash
FROM [OWNERID].dbo.person a
where
--a.iid >= '[MIN_IID]' and a.iid <='[MAX_IID]'
--a.iid >= 0 and a.iid <='41954489'
--and
last_updated_date >= DATEADD(day, -1,'&INGEST_YYYYMMDD') and last_updated_date < '&END_YYYYMMDD'
